/**
 * Static catalog of car makes and models used in admin forms.
 * Comprehensive list of well-known makes worldwide and their popular models.
 * "Autre" lets the admin type a custom value when not listed.
 */

export const CAR_CATALOG: Record<string, string[]> = {
  "Abarth": ["500", "595", "695", "124 Spider"],
  "Acura": ["ILX", "TLX", "RLX", "MDX", "RDX", "NSX", "Integra"],
  "Alfa Romeo": ["Giulia", "Giulietta", "Stelvio", "Tonale", "MiTo", "4C", "159", "Brera"],
  "Aston Martin": ["DB9", "DB11", "DB12", "Vantage", "DBS", "DBX", "Rapide", "Vanquish"],
  "Audi": ["A1", "A2", "A3", "A3 Sportback", "A4", "A4 Avant", "A5", "A6", "A6 Avant", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "TT", "R8", "e-tron", "e-tron GT", "RS3", "RS4", "RS5", "RS6", "RS7", "S3", "S4", "S5"],
  "Bentley": ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne"],
  "BMW": ["Série 1", "Série 2", "Série 2 Active Tourer", "Série 3", "Série 3 320d", "Série 3 Touring", "Série 4", "Série 5", "Série 5 Touring", "Série 6", "Série 7", "Série 8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z3", "Z4", "i3", "i4", "i5", "i7", "i8", "iX", "iX1", "iX3", "M2", "M3", "M4", "M5", "M8"],
  "Bugatti": ["Chiron", "Veyron", "Divo", "Centodieci"],
  "Buick": ["Enclave", "Encore", "Envision", "Regal", "LaCrosse"],
  "BYD": ["Atto 3", "Dolphin", "Han", "Seal", "Tang", "Song"],
  "Cadillac": ["ATS", "CTS", "CT4", "CT5", "CT6", "Escalade", "XT4", "XT5", "XT6", "Lyriq"],
  "Chery": ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo 5", "Arrizo 6"],
  "Chevrolet": ["Spark", "Aveo", "Sonic", "Cruze", "Malibu", "Camaro", "Corvette", "Impala", "Trax", "Trailblazer", "Equinox", "Blazer", "Traverse", "Tahoe", "Suburban", "Silverado", "Colorado", "Bolt", "Captiva", "Optra"],
  "Chrysler": ["300", "Pacifica", "Voyager", "PT Cruiser"],
  "Citroën": ["C1", "C2", "C3", "C3 Aircross", "C3 Shine", "C4", "C4 Cactus", "C4 Picasso", "C5", "C5 Aircross", "C5 X", "C6", "C8", "DS3", "DS4", "DS5", "Berlingo", "Jumpy", "Jumper", "Saxo", "Xsara", "Xantia", "Nemo", "Spacetourer", "ë-C4"],
  "Cupra": ["Born", "Formentor", "Leon", "Ateca", "Tavascan"],
  "Dacia": ["Sandero", "Sandero Stepway", "Logan", "Logan MCV", "Duster", "Duster Prestige", "Lodgy", "Dokker", "Spring", "Jogger"],
  "Daewoo": ["Matiz", "Lanos", "Nubira", "Leganza", "Tacuma"],
  "Daihatsu": ["Terios", "Sirion", "Materia", "Copen"],
  "Dodge": ["Charger", "Challenger", "Durango", "Journey", "Ram 1500", "Caliber", "Avenger"],
  "DS": ["DS3", "DS3 Crossback", "DS4", "DS5", "DS7 Crossback", "DS9"],
  "Ferrari": ["488", "F8 Tributo", "Roma", "Portofino", "SF90", "812 Superfast", "296 GTB", "Purosangue", "California", "458 Italia", "LaFerrari"],
  "Fiat": ["500", "500X", "500L", "500e", "Panda", "Punto", "Tipo", "Bravo", "Doblo", "Ducato", "Fiorino", "Linea", "Multipla", "Qubo", "Stilo", "124 Spider"],
  "Ford": ["Ka", "Fiesta", "Focus", "Focus ST", "Mondeo", "Fusion", "Galaxy", "S-Max", "C-Max", "B-Max", "Kuga", "Puma", "EcoSport", "Edge", "Explorer", "Escape", "Bronco", "Mustang", "Mustang Mach-E", "Ranger", "F-150", "Transit", "Tourneo", "Escort"],
  "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "GMC": ["Sierra", "Yukon", "Acadia", "Terrain", "Canyon", "Hummer EV"],
  "Great Wall": ["Hover", "Wingle", "H6", "Poer"],
  "Haval": ["H2", "H6", "H9", "Jolion"],
  "Honda": ["Jazz", "Fit", "City", "Civic", "Civic Type R", "Accord", "Insight", "CR-V", "HR-V", "ZR-V", "Pilot", "Passport", "Ridgeline", "Odyssey", "e", "NSX", "Legend", "Stream"],
  "Hummer": ["H1", "H2", "H3", "EV"],
  "Hyundai": ["i10", "i20", "i30", "i40", "Accent", "Elantra", "Sonata", "Ioniq", "Ioniq 5", "Ioniq 6", "Kona", "Bayon", "Tucson", "Santa Fe", "Palisade", "Venue", "Creta", "Veloster", "Genesis", "H1", "Staria"],
  "Infiniti": ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX60", "QX70", "QX80"],
  "Isuzu": ["D-Max", "MU-X", "Trooper", "Rodeo"],
  "Jaguar": ["XE", "XF", "XJ", "F-Type", "E-Pace", "F-Pace", "I-Pace"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator", "Avenger", "Wagoneer", "Patriot"],
  "Kia": ["Picanto", "Rio", "Stonic", "Ceed", "Cerato", "Forte", "Optima", "K5", "Stinger", "Soul", "Niro", "EV6", "Sportage", "Sorento", "Telluride", "Carens", "Carnival", "Mohave"],
  "Lada": ["Niva", "Vesta", "Granta", "Largus", "Priora"],
  "Lamborghini": ["Huracán", "Aventador", "Urus", "Revuelto", "Gallardo", "Murciélago"],
  "Lancia": ["Ypsilon", "Delta", "Musa", "Phedra"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Freelander"],
  "Lexus": ["CT", "IS", "ES", "GS", "LS", "UX", "NX", "RX", "GX", "LX", "RC", "LC", "RZ"],
  "Lincoln": ["MKC", "MKZ", "Continental", "Navigator", "Aviator", "Nautilus", "Corsair"],
  "Lotus": ["Elise", "Exige", "Evora", "Emira", "Eletre", "Evija"],
  "Lucid": ["Air", "Gravity"],
  "Maserati": ["Ghibli", "Quattroporte", "Levante", "Grecale", "MC20", "GranTurismo"],
  "Maybach": ["S-Class", "GLS"],
  "Mazda": ["Mazda 2", "Mazda 3", "Mazda 5", "Mazda 6", "MX-5", "CX-3", "CX-30", "CX-5", "CX-50", "CX-60", "CX-70", "CX-80", "CX-90", "RX-7", "RX-8", "BT-50"],
  "McLaren": ["570S", "600LT", "720S", "765LT", "Artura", "GT", "P1", "Senna"],
  "Mercedes-Benz": ["Classe A", "Classe B", "Classe C", "Classe C 220d", "Classe E", "Classe S", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "SL", "SLC", "SLK", "AMG GT", "EQA", "EQB", "EQC", "EQE", "EQS", "EQV", "Vito", "Viano", "Sprinter", "Citan"],
  "MG": ["MG3", "MG4", "MG5", "ZS", "HS", "EHS", "Marvel R", "Cyberster"],
  "Mini": ["Cooper", "Cooper S", "Clubman", "Countryman", "Paceman", "Cabrio", "Electric"],
  "Mitsubishi": ["Mirage", "Space Star", "Lancer", "ASX", "Eclipse Cross", "Outlander", "Pajero", "Pajero Sport", "Pajero Pinin", "Montero", "L200", "Colt", "Galant", "Carisma"],
  "Nissan": ["Micra", "Note", "Pulsar", "Sentra", "Almera", "Sunny", "Tiida", "Sylphy", "Versa", "Leaf", "Juke", "Qashqai", "X-Trail", "Murano", "Pathfinder", "Patrol", "Armada", "Terrano", "Navara", "Frontier", "NV200", "Ariya", "GT-R", "370Z", "350Z", "Z"],
  "Opel": ["Adam", "Karl", "Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland", "Zafira", "Meriva", "Antara", "Combo", "Vivaro", "Movano", "Frontera"],
  "Peugeot": ["108", "208", "208 GT Line", "301", "308", "308 SW", "408", "508", "2008", "3008", "5008", "Partner", "Rifter", "Traveller", "Boxer", "Expert", "RCZ", "iOn", "e-208", "e-2008"],
  "Polestar": ["1", "2", "3", "4"],
  "Porsche": ["911", "718 Cayman", "718 Boxster", "Panamera", "Macan", "Cayenne", "Taycan", "918 Spyder"],
  "Proton": ["Saga", "Persona", "Iriz", "X50", "X70"],
  "RAM": ["1500", "2500", "3500", "ProMaster"],
  "Renault": ["Twingo", "Clio", "Clio 5 Intens", "Symbol", "Mégane", "Mégane E-Tech", "Fluence", "Talisman", "Laguna", "Espace", "Scénic", "Grand Scénic", "Captur", "Kadjar", "Koleos", "Arkana", "Austral", "Rafale", "Kangoo", "Trafic", "Master", "Zoe", "Twizy", "Modus"],
  "Rolls-Royce": ["Ghost", "Phantom", "Wraith", "Dawn", "Cullinan", "Spectre"],
  "Saab": ["9-3", "9-5", "9-7X"],
  "Seat": ["Mii", "Ibiza", "Leon", "Toledo", "Cordoba", "Altea", "Exeo", "Arona", "Ateca", "Tarraco", "Alhambra"],
  "Skoda": ["Citigo", "Fabia", "Rapid", "Scala", "Octavia", "Superb", "Karoq", "Kodiaq", "Kamiq", "Yeti", "Enyaq", "Roomster"],
  "Smart": ["Fortwo", "Forfour", "Roadster", "#1", "#3"],
  "SsangYong": ["Tivoli", "Korando", "Rexton", "Musso", "Actyon"],
  "Subaru": ["Impreza", "WRX", "Legacy", "Outback", "Forester", "XV", "Crosstrek", "Ascent", "BRZ", "Solterra"],
  "Suzuki": ["Alto", "Celerio", "Swift", "Baleno", "Ignis", "Jimny", "Vitara", "S-Cross", "SX4", "Across", "Swace", "Grand Vitara", "Splash"],
  "Tata": ["Nano", "Indica", "Indigo", "Tiago", "Tigor", "Nexon", "Harrier", "Safari", "Punch"],
  "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
  "Toyota": ["Aygo", "Yaris", "Yaris Cross", "Corolla", "Corolla Cross", "Camry", "Avensis", "Prius", "Mirai", "C-HR", "RAV4", "bZ4X", "Highlander", "Sequoia", "4Runner", "Fortuner", "Land Cruiser", "Land Cruiser Prado", "Hilux", "Tacoma", "Tundra", "Sienna", "Verso", "Auris", "GR Yaris", "GR86", "Supra"],
  "Vauxhall": ["Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland"],
  "Volkswagen": ["Up!", "Polo", "Golf", "Golf 7 GTD", "Golf GTI", "Jetta", "Passat", "Arteon", "Beetle", "Scirocco", "Eos", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Touran", "Sharan", "Caddy", "Transporter", "Multivan", "Amarok", "ID.3", "ID.4", "ID.5", "ID.6", "ID.7", "ID. Buzz"],
  "Volvo": ["S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90", "C30", "C40", "EX30", "EX90"],
};

export const CAR_MAKES = Object.keys(CAR_CATALOG).sort((a, b) => a.localeCompare(b));
