/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendeurRouteImport } from './routes/vendeur'
import { Route as VehiculesRouteImport } from './routes/vehicules'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionEnAttenteRouteImport } from './routes/inscription-en-attente'
import { Route as HomeV3RouteImport } from './routes/home-v3'
import { Route as HomeV2RouteImport } from './routes/home-v2'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as CommentCaMarcheVendeurRouteImport } from './routes/comment-ca-marche-vendeur'
import { Route as CommentCaMarcheAcheteurRouteImport } from './routes/comment-ca-marche-acheteur'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcheteurRouteImport } from './routes/acheteur'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendeurIndexRouteImport } from './routes/vendeur.index'
import { Route as ExpertIndexRouteImport } from './routes/expert.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AcheteurIndexRouteImport } from './routes/acheteur.index'
import { Route as VendeurVoituresRouteImport } from './routes/vendeur.voitures'
import { Route as VendeurPaiementsRouteImport } from './routes/vendeur.paiements'
import { Route as VendeurHistoriqueRouteImport } from './routes/vendeur.historique'
import { Route as VendeurEncheresRouteImport } from './routes/vendeur.encheres'
import { Route as ExpertInspectionsRouteImport } from './routes/expert.inspections'
import { Route as ExpertHistoriqueRouteImport } from './routes/expert.historique'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AuctionsAuctionIdRouteImport } from './routes/auctions.$auctionId'
import { Route as AdminVoituresRouteImport } from './routes/admin.voitures'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminValidationsRouteImport } from './routes/admin.validations'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as AdminPaiementsRouteImport } from './routes/admin.paiements'
import { Route as AdminExpertsRouteImport } from './routes/admin.experts'
import { Route as AdminEncheresRouteImport } from './routes/admin.encheres'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AcheteurPaiementsRouteImport } from './routes/acheteur.paiements'
import { Route as AcheteurNotificationsRouteImport } from './routes/acheteur.notifications'
import { Route as AcheteurEncheresRouteImport } from './routes/acheteur.encheres'
import { Route as AcheteurCautionPaiementRouteImport } from './routes/acheteur.caution-paiement'
import { Route as AcheteurCautionRouteImport } from './routes/acheteur.caution'
import { Route as ExpertInspectionsInspectionIdRouteImport } from './routes/expert.inspections.$inspectionId'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api/public/seed-demo'
import { Route as ApiPublicCmiInitRouteImport } from './routes/api/public/cmi-init'
import { Route as ApiPublicCmiCallbackRouteImport } from './routes/api/public/cmi-callback'
import { Route as ApiPublicAdminDeleteUserRouteImport } from './routes/api/public/admin-delete-user'
import { Route as ApiPublicAdminCreateUserRouteImport } from './routes/api/public/admin-create-user'
import { Route as AcheteurEncherirAuctionIdRouteImport } from './routes/acheteur.encherir.$auctionId'

const VendeurRoute = VendeurRouteImport.update({
  id: '/vendeur',
  path: '/vendeur',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesRoute = VehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionEnAttenteRoute = InscriptionEnAttenteRouteImport.update({
  id: '/inscription-en-attente',
  path: '/inscription-en-attente',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeV3Route = HomeV3RouteImport.update({
  id: '/home-v3',
  path: '/home-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeV2Route = HomeV2RouteImport.update({
  id: '/home-v2',
  path: '/home-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheVendeurRoute = CommentCaMarcheVendeurRouteImport.update({
  id: '/comment-ca-marche-vendeur',
  path: '/comment-ca-marche-vendeur',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheAcheteurRoute = CommentCaMarcheAcheteurRouteImport.update({
  id: '/comment-ca-marche-acheteur',
  path: '/comment-ca-marche-acheteur',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcheteurRoute = AcheteurRouteImport.update({
  id: '/acheteur',
  path: '/acheteur',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendeurIndexRoute = VendeurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendeurRoute,
} as any)
const ExpertIndexRoute = ExpertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AcheteurIndexRoute = AcheteurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcheteurRoute,
} as any)
const VendeurVoituresRoute = VendeurVoituresRouteImport.update({
  id: '/voitures',
  path: '/voitures',
  getParentRoute: () => VendeurRoute,
} as any)
const VendeurPaiementsRoute = VendeurPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => VendeurRoute,
} as any)
const VendeurHistoriqueRoute = VendeurHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => VendeurRoute,
} as any)
const VendeurEncheresRoute = VendeurEncheresRouteImport.update({
  id: '/encheres',
  path: '/encheres',
  getParentRoute: () => VendeurRoute,
} as any)
const ExpertInspectionsRoute = ExpertInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertHistoriqueRoute = ExpertHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => ExpertRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionIdRoute = AuctionsAuctionIdRouteImport.update({
  id: '/auctions/$auctionId',
  path: '/auctions/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVoituresRoute = AdminVoituresRouteImport.update({
  id: '/voitures',
  path: '/voitures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminValidationsRoute = AdminValidationsRouteImport.update({
  id: '/validations',
  path: '/validations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpertsRoute = AdminExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEncheresRoute = AdminEncheresRouteImport.update({
  id: '/encheres',
  path: '/encheres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AcheteurPaiementsRoute = AcheteurPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AcheteurRoute,
} as any)
const AcheteurNotificationsRoute = AcheteurNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AcheteurRoute,
} as any)
const AcheteurEncheresRoute = AcheteurEncheresRouteImport.update({
  id: '/encheres',
  path: '/encheres',
  getParentRoute: () => AcheteurRoute,
} as any)
const AcheteurCautionPaiementRoute = AcheteurCautionPaiementRouteImport.update({
  id: '/caution-paiement',
  path: '/caution-paiement',
  getParentRoute: () => AcheteurRoute,
} as any)
const AcheteurCautionRoute = AcheteurCautionRouteImport.update({
  id: '/caution',
  path: '/caution',
  getParentRoute: () => AcheteurRoute,
} as any)
const ExpertInspectionsInspectionIdRoute =
  ExpertInspectionsInspectionIdRouteImport.update({
    id: '/$inspectionId',
    path: '/$inspectionId',
    getParentRoute: () => ExpertInspectionsRoute,
  } as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmiInitRoute = ApiPublicCmiInitRouteImport.update({
  id: '/api/public/cmi-init',
  path: '/api/public/cmi-init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmiCallbackRoute = ApiPublicCmiCallbackRouteImport.update({
  id: '/api/public/cmi-callback',
  path: '/api/public/cmi-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDeleteUserRoute =
  ApiPublicAdminDeleteUserRouteImport.update({
    id: '/api/public/admin-delete-user',
    path: '/api/public/admin-delete-user',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminCreateUserRoute =
  ApiPublicAdminCreateUserRouteImport.update({
    id: '/api/public/admin-create-user',
    path: '/api/public/admin-create-user',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcheteurEncherirAuctionIdRoute =
  AcheteurEncherirAuctionIdRouteImport.update({
    id: '/encherir/$auctionId',
    path: '/encherir/$auctionId',
    getParentRoute: () => AcheteurRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acheteur': typeof AcheteurRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comment-ca-marche-acheteur': typeof CommentCaMarcheAcheteurRoute
  '/comment-ca-marche-vendeur': typeof CommentCaMarcheVendeurRoute
  '/expert': typeof ExpertRouteWithChildren
  '/home-v2': typeof HomeV2Route
  '/home-v3': typeof HomeV3Route
  '/inscription-en-attente': typeof InscriptionEnAttenteRoute
  '/login': typeof LoginRoute
  '/trust': typeof TrustRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/vehicules': typeof VehiculesRoute
  '/vendeur': typeof VendeurRouteWithChildren
  '/acheteur/caution': typeof AcheteurCautionRoute
  '/acheteur/caution-paiement': typeof AcheteurCautionPaiementRoute
  '/acheteur/encheres': typeof AcheteurEncheresRoute
  '/acheteur/notifications': typeof AcheteurNotificationsRoute
  '/acheteur/paiements': typeof AcheteurPaiementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/encheres': typeof AdminEncheresRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/validations': typeof AdminValidationsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/voitures': typeof AdminVoituresRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/expert/historique': typeof ExpertHistoriqueRoute
  '/expert/inspections': typeof ExpertInspectionsRouteWithChildren
  '/vendeur/encheres': typeof VendeurEncheresRoute
  '/vendeur/historique': typeof VendeurHistoriqueRoute
  '/vendeur/paiements': typeof VendeurPaiementsRoute
  '/vendeur/voitures': typeof VendeurVoituresRoute
  '/acheteur/': typeof AcheteurIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/vendeur/': typeof VendeurIndexRoute
  '/acheteur/encherir/$auctionId': typeof AcheteurEncherirAuctionIdRoute
  '/api/public/admin-create-user': typeof ApiPublicAdminCreateUserRoute
  '/api/public/admin-delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/cmi-callback': typeof ApiPublicCmiCallbackRoute
  '/api/public/cmi-init': typeof ApiPublicCmiInitRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/expert/inspections/$inspectionId': typeof ExpertInspectionsInspectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comment-ca-marche-acheteur': typeof CommentCaMarcheAcheteurRoute
  '/comment-ca-marche-vendeur': typeof CommentCaMarcheVendeurRoute
  '/home-v2': typeof HomeV2Route
  '/home-v3': typeof HomeV3Route
  '/inscription-en-attente': typeof InscriptionEnAttenteRoute
  '/login': typeof LoginRoute
  '/trust': typeof TrustRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/vehicules': typeof VehiculesRoute
  '/acheteur/caution': typeof AcheteurCautionRoute
  '/acheteur/caution-paiement': typeof AcheteurCautionPaiementRoute
  '/acheteur/encheres': typeof AcheteurEncheresRoute
  '/acheteur/notifications': typeof AcheteurNotificationsRoute
  '/acheteur/paiements': typeof AcheteurPaiementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/encheres': typeof AdminEncheresRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/validations': typeof AdminValidationsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/voitures': typeof AdminVoituresRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/expert/historique': typeof ExpertHistoriqueRoute
  '/expert/inspections': typeof ExpertInspectionsRouteWithChildren
  '/vendeur/encheres': typeof VendeurEncheresRoute
  '/vendeur/historique': typeof VendeurHistoriqueRoute
  '/vendeur/paiements': typeof VendeurPaiementsRoute
  '/vendeur/voitures': typeof VendeurVoituresRoute
  '/acheteur': typeof AcheteurIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auctions': typeof AuctionsIndexRoute
  '/events': typeof EventsIndexRoute
  '/expert': typeof ExpertIndexRoute
  '/vendeur': typeof VendeurIndexRoute
  '/acheteur/encherir/$auctionId': typeof AcheteurEncherirAuctionIdRoute
  '/api/public/admin-create-user': typeof ApiPublicAdminCreateUserRoute
  '/api/public/admin-delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/cmi-callback': typeof ApiPublicCmiCallbackRoute
  '/api/public/cmi-init': typeof ApiPublicCmiInitRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/expert/inspections/$inspectionId': typeof ExpertInspectionsInspectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acheteur': typeof AcheteurRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comment-ca-marche-acheteur': typeof CommentCaMarcheAcheteurRoute
  '/comment-ca-marche-vendeur': typeof CommentCaMarcheVendeurRoute
  '/expert': typeof ExpertRouteWithChildren
  '/home-v2': typeof HomeV2Route
  '/home-v3': typeof HomeV3Route
  '/inscription-en-attente': typeof InscriptionEnAttenteRoute
  '/login': typeof LoginRoute
  '/trust': typeof TrustRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/vehicules': typeof VehiculesRoute
  '/vendeur': typeof VendeurRouteWithChildren
  '/acheteur/caution': typeof AcheteurCautionRoute
  '/acheteur/caution-paiement': typeof AcheteurCautionPaiementRoute
  '/acheteur/encheres': typeof AcheteurEncheresRoute
  '/acheteur/notifications': typeof AcheteurNotificationsRoute
  '/acheteur/paiements': typeof AcheteurPaiementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/encheres': typeof AdminEncheresRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/validations': typeof AdminValidationsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/voitures': typeof AdminVoituresRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/expert/historique': typeof ExpertHistoriqueRoute
  '/expert/inspections': typeof ExpertInspectionsRouteWithChildren
  '/vendeur/encheres': typeof VendeurEncheresRoute
  '/vendeur/historique': typeof VendeurHistoriqueRoute
  '/vendeur/paiements': typeof VendeurPaiementsRoute
  '/vendeur/voitures': typeof VendeurVoituresRoute
  '/acheteur/': typeof AcheteurIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/vendeur/': typeof VendeurIndexRoute
  '/acheteur/encherir/$auctionId': typeof AcheteurEncherirAuctionIdRoute
  '/api/public/admin-create-user': typeof ApiPublicAdminCreateUserRoute
  '/api/public/admin-delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/cmi-callback': typeof ApiPublicCmiCallbackRoute
  '/api/public/cmi-init': typeof ApiPublicCmiInitRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/expert/inspections/$inspectionId': typeof ExpertInspectionsInspectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acheteur'
    | '/admin'
    | '/comment-ca-marche'
    | '/comment-ca-marche-acheteur'
    | '/comment-ca-marche-vendeur'
    | '/expert'
    | '/home-v2'
    | '/home-v3'
    | '/inscription-en-attente'
    | '/login'
    | '/trust'
    | '/unauthorized'
    | '/vehicules'
    | '/vendeur'
    | '/acheteur/caution'
    | '/acheteur/caution-paiement'
    | '/acheteur/encheres'
    | '/acheteur/notifications'
    | '/acheteur/paiements'
    | '/admin/analytics'
    | '/admin/encheres'
    | '/admin/experts'
    | '/admin/paiements'
    | '/admin/utilisateurs'
    | '/admin/validations'
    | '/admin/verifications'
    | '/admin/voitures'
    | '/auctions/$auctionId'
    | '/events/$eventId'
    | '/expert/historique'
    | '/expert/inspections'
    | '/vendeur/encheres'
    | '/vendeur/historique'
    | '/vendeur/paiements'
    | '/vendeur/voitures'
    | '/acheteur/'
    | '/admin/'
    | '/auctions/'
    | '/events/'
    | '/expert/'
    | '/vendeur/'
    | '/acheteur/encherir/$auctionId'
    | '/api/public/admin-create-user'
    | '/api/public/admin-delete-user'
    | '/api/public/cmi-callback'
    | '/api/public/cmi-init'
    | '/api/public/seed-demo'
    | '/expert/inspections/$inspectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comment-ca-marche'
    | '/comment-ca-marche-acheteur'
    | '/comment-ca-marche-vendeur'
    | '/home-v2'
    | '/home-v3'
    | '/inscription-en-attente'
    | '/login'
    | '/trust'
    | '/unauthorized'
    | '/vehicules'
    | '/acheteur/caution'
    | '/acheteur/caution-paiement'
    | '/acheteur/encheres'
    | '/acheteur/notifications'
    | '/acheteur/paiements'
    | '/admin/analytics'
    | '/admin/encheres'
    | '/admin/experts'
    | '/admin/paiements'
    | '/admin/utilisateurs'
    | '/admin/validations'
    | '/admin/verifications'
    | '/admin/voitures'
    | '/auctions/$auctionId'
    | '/events/$eventId'
    | '/expert/historique'
    | '/expert/inspections'
    | '/vendeur/encheres'
    | '/vendeur/historique'
    | '/vendeur/paiements'
    | '/vendeur/voitures'
    | '/acheteur'
    | '/admin'
    | '/auctions'
    | '/events'
    | '/expert'
    | '/vendeur'
    | '/acheteur/encherir/$auctionId'
    | '/api/public/admin-create-user'
    | '/api/public/admin-delete-user'
    | '/api/public/cmi-callback'
    | '/api/public/cmi-init'
    | '/api/public/seed-demo'
    | '/expert/inspections/$inspectionId'
  id:
    | '__root__'
    | '/'
    | '/acheteur'
    | '/admin'
    | '/comment-ca-marche'
    | '/comment-ca-marche-acheteur'
    | '/comment-ca-marche-vendeur'
    | '/expert'
    | '/home-v2'
    | '/home-v3'
    | '/inscription-en-attente'
    | '/login'
    | '/trust'
    | '/unauthorized'
    | '/vehicules'
    | '/vendeur'
    | '/acheteur/caution'
    | '/acheteur/caution-paiement'
    | '/acheteur/encheres'
    | '/acheteur/notifications'
    | '/acheteur/paiements'
    | '/admin/analytics'
    | '/admin/encheres'
    | '/admin/experts'
    | '/admin/paiements'
    | '/admin/utilisateurs'
    | '/admin/validations'
    | '/admin/verifications'
    | '/admin/voitures'
    | '/auctions/$auctionId'
    | '/events/$eventId'
    | '/expert/historique'
    | '/expert/inspections'
    | '/vendeur/encheres'
    | '/vendeur/historique'
    | '/vendeur/paiements'
    | '/vendeur/voitures'
    | '/acheteur/'
    | '/admin/'
    | '/auctions/'
    | '/events/'
    | '/expert/'
    | '/vendeur/'
    | '/acheteur/encherir/$auctionId'
    | '/api/public/admin-create-user'
    | '/api/public/admin-delete-user'
    | '/api/public/cmi-callback'
    | '/api/public/cmi-init'
    | '/api/public/seed-demo'
    | '/expert/inspections/$inspectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcheteurRoute: typeof AcheteurRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  CommentCaMarcheAcheteurRoute: typeof CommentCaMarcheAcheteurRoute
  CommentCaMarcheVendeurRoute: typeof CommentCaMarcheVendeurRoute
  ExpertRoute: typeof ExpertRouteWithChildren
  HomeV2Route: typeof HomeV2Route
  HomeV3Route: typeof HomeV3Route
  InscriptionEnAttenteRoute: typeof InscriptionEnAttenteRoute
  LoginRoute: typeof LoginRoute
  TrustRoute: typeof TrustRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VehiculesRoute: typeof VehiculesRoute
  VendeurRoute: typeof VendeurRouteWithChildren
  AuctionsAuctionIdRoute: typeof AuctionsAuctionIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicAdminCreateUserRoute: typeof ApiPublicAdminCreateUserRoute
  ApiPublicAdminDeleteUserRoute: typeof ApiPublicAdminDeleteUserRoute
  ApiPublicCmiCallbackRoute: typeof ApiPublicCmiCallbackRoute
  ApiPublicCmiInitRoute: typeof ApiPublicCmiInitRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendeur': {
      id: '/vendeur'
      path: '/vendeur'
      fullPath: '/vendeur'
      preLoaderRoute: typeof VendeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-en-attente': {
      id: '/inscription-en-attente'
      path: '/inscription-en-attente'
      fullPath: '/inscription-en-attente'
      preLoaderRoute: typeof InscriptionEnAttenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-v3': {
      id: '/home-v3'
      path: '/home-v3'
      fullPath: '/home-v3'
      preLoaderRoute: typeof HomeV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-v2': {
      id: '/home-v2'
      path: '/home-v2'
      fullPath: '/home-v2'
      preLoaderRoute: typeof HomeV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche-vendeur': {
      id: '/comment-ca-marche-vendeur'
      path: '/comment-ca-marche-vendeur'
      fullPath: '/comment-ca-marche-vendeur'
      preLoaderRoute: typeof CommentCaMarcheVendeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche-acheteur': {
      id: '/comment-ca-marche-acheteur'
      path: '/comment-ca-marche-acheteur'
      fullPath: '/comment-ca-marche-acheteur'
      preLoaderRoute: typeof CommentCaMarcheAcheteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acheteur': {
      id: '/acheteur'
      path: '/acheteur'
      fullPath: '/acheteur'
      preLoaderRoute: typeof AcheteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendeur/': {
      id: '/vendeur/'
      path: '/'
      fullPath: '/vendeur/'
      preLoaderRoute: typeof VendeurIndexRouteImport
      parentRoute: typeof VendeurRoute
    }
    '/expert/': {
      id: '/expert/'
      path: '/'
      fullPath: '/expert/'
      preLoaderRoute: typeof ExpertIndexRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/acheteur/': {
      id: '/acheteur/'
      path: '/'
      fullPath: '/acheteur/'
      preLoaderRoute: typeof AcheteurIndexRouteImport
      parentRoute: typeof AcheteurRoute
    }
    '/vendeur/voitures': {
      id: '/vendeur/voitures'
      path: '/voitures'
      fullPath: '/vendeur/voitures'
      preLoaderRoute: typeof VendeurVoituresRouteImport
      parentRoute: typeof VendeurRoute
    }
    '/vendeur/paiements': {
      id: '/vendeur/paiements'
      path: '/paiements'
      fullPath: '/vendeur/paiements'
      preLoaderRoute: typeof VendeurPaiementsRouteImport
      parentRoute: typeof VendeurRoute
    }
    '/vendeur/historique': {
      id: '/vendeur/historique'
      path: '/historique'
      fullPath: '/vendeur/historique'
      preLoaderRoute: typeof VendeurHistoriqueRouteImport
      parentRoute: typeof VendeurRoute
    }
    '/vendeur/encheres': {
      id: '/vendeur/encheres'
      path: '/encheres'
      fullPath: '/vendeur/encheres'
      preLoaderRoute: typeof VendeurEncheresRouteImport
      parentRoute: typeof VendeurRoute
    }
    '/expert/inspections': {
      id: '/expert/inspections'
      path: '/inspections'
      fullPath: '/expert/inspections'
      preLoaderRoute: typeof ExpertInspectionsRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/historique': {
      id: '/expert/historique'
      path: '/historique'
      fullPath: '/expert/historique'
      preLoaderRoute: typeof ExpertHistoriqueRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionId': {
      id: '/auctions/$auctionId'
      path: '/auctions/$auctionId'
      fullPath: '/auctions/$auctionId'
      preLoaderRoute: typeof AuctionsAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voitures': {
      id: '/admin/voitures'
      path: '/voitures'
      fullPath: '/admin/voitures'
      preLoaderRoute: typeof AdminVoituresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/validations': {
      id: '/admin/validations'
      path: '/validations'
      fullPath: '/admin/validations'
      preLoaderRoute: typeof AdminValidationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experts': {
      id: '/admin/experts'
      path: '/experts'
      fullPath: '/admin/experts'
      preLoaderRoute: typeof AdminExpertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/encheres': {
      id: '/admin/encheres'
      path: '/encheres'
      fullPath: '/admin/encheres'
      preLoaderRoute: typeof AdminEncheresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/acheteur/paiements': {
      id: '/acheteur/paiements'
      path: '/paiements'
      fullPath: '/acheteur/paiements'
      preLoaderRoute: typeof AcheteurPaiementsRouteImport
      parentRoute: typeof AcheteurRoute
    }
    '/acheteur/notifications': {
      id: '/acheteur/notifications'
      path: '/notifications'
      fullPath: '/acheteur/notifications'
      preLoaderRoute: typeof AcheteurNotificationsRouteImport
      parentRoute: typeof AcheteurRoute
    }
    '/acheteur/encheres': {
      id: '/acheteur/encheres'
      path: '/encheres'
      fullPath: '/acheteur/encheres'
      preLoaderRoute: typeof AcheteurEncheresRouteImport
      parentRoute: typeof AcheteurRoute
    }
    '/acheteur/caution-paiement': {
      id: '/acheteur/caution-paiement'
      path: '/caution-paiement'
      fullPath: '/acheteur/caution-paiement'
      preLoaderRoute: typeof AcheteurCautionPaiementRouteImport
      parentRoute: typeof AcheteurRoute
    }
    '/acheteur/caution': {
      id: '/acheteur/caution'
      path: '/caution'
      fullPath: '/acheteur/caution'
      preLoaderRoute: typeof AcheteurCautionRouteImport
      parentRoute: typeof AcheteurRoute
    }
    '/expert/inspections/$inspectionId': {
      id: '/expert/inspections/$inspectionId'
      path: '/$inspectionId'
      fullPath: '/expert/inspections/$inspectionId'
      preLoaderRoute: typeof ExpertInspectionsInspectionIdRouteImport
      parentRoute: typeof ExpertInspectionsRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cmi-init': {
      id: '/api/public/cmi-init'
      path: '/api/public/cmi-init'
      fullPath: '/api/public/cmi-init'
      preLoaderRoute: typeof ApiPublicCmiInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cmi-callback': {
      id: '/api/public/cmi-callback'
      path: '/api/public/cmi-callback'
      fullPath: '/api/public/cmi-callback'
      preLoaderRoute: typeof ApiPublicCmiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-delete-user': {
      id: '/api/public/admin-delete-user'
      path: '/api/public/admin-delete-user'
      fullPath: '/api/public/admin-delete-user'
      preLoaderRoute: typeof ApiPublicAdminDeleteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-create-user': {
      id: '/api/public/admin-create-user'
      path: '/api/public/admin-create-user'
      fullPath: '/api/public/admin-create-user'
      preLoaderRoute: typeof ApiPublicAdminCreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acheteur/encherir/$auctionId': {
      id: '/acheteur/encherir/$auctionId'
      path: '/encherir/$auctionId'
      fullPath: '/acheteur/encherir/$auctionId'
      preLoaderRoute: typeof AcheteurEncherirAuctionIdRouteImport
      parentRoute: typeof AcheteurRoute
    }
  }
}

interface AcheteurRouteChildren {
  AcheteurCautionRoute: typeof AcheteurCautionRoute
  AcheteurCautionPaiementRoute: typeof AcheteurCautionPaiementRoute
  AcheteurEncheresRoute: typeof AcheteurEncheresRoute
  AcheteurNotificationsRoute: typeof AcheteurNotificationsRoute
  AcheteurPaiementsRoute: typeof AcheteurPaiementsRoute
  AcheteurIndexRoute: typeof AcheteurIndexRoute
  AcheteurEncherirAuctionIdRoute: typeof AcheteurEncherirAuctionIdRoute
}

const AcheteurRouteChildren: AcheteurRouteChildren = {
  AcheteurCautionRoute: AcheteurCautionRoute,
  AcheteurCautionPaiementRoute: AcheteurCautionPaiementRoute,
  AcheteurEncheresRoute: AcheteurEncheresRoute,
  AcheteurNotificationsRoute: AcheteurNotificationsRoute,
  AcheteurPaiementsRoute: AcheteurPaiementsRoute,
  AcheteurIndexRoute: AcheteurIndexRoute,
  AcheteurEncherirAuctionIdRoute: AcheteurEncherirAuctionIdRoute,
}

const AcheteurRouteWithChildren = AcheteurRoute._addFileChildren(
  AcheteurRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminEncheresRoute: typeof AdminEncheresRoute
  AdminExpertsRoute: typeof AdminExpertsRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminValidationsRoute: typeof AdminValidationsRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminVoituresRoute: typeof AdminVoituresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminEncheresRoute: AdminEncheresRoute,
  AdminExpertsRoute: AdminExpertsRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminValidationsRoute: AdminValidationsRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminVoituresRoute: AdminVoituresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExpertInspectionsRouteChildren {
  ExpertInspectionsInspectionIdRoute: typeof ExpertInspectionsInspectionIdRoute
}

const ExpertInspectionsRouteChildren: ExpertInspectionsRouteChildren = {
  ExpertInspectionsInspectionIdRoute: ExpertInspectionsInspectionIdRoute,
}

const ExpertInspectionsRouteWithChildren =
  ExpertInspectionsRoute._addFileChildren(ExpertInspectionsRouteChildren)

interface ExpertRouteChildren {
  ExpertHistoriqueRoute: typeof ExpertHistoriqueRoute
  ExpertInspectionsRoute: typeof ExpertInspectionsRouteWithChildren
  ExpertIndexRoute: typeof ExpertIndexRoute
}

const ExpertRouteChildren: ExpertRouteChildren = {
  ExpertHistoriqueRoute: ExpertHistoriqueRoute,
  ExpertInspectionsRoute: ExpertInspectionsRouteWithChildren,
  ExpertIndexRoute: ExpertIndexRoute,
}

const ExpertRouteWithChildren =
  ExpertRoute._addFileChildren(ExpertRouteChildren)

interface VendeurRouteChildren {
  VendeurEncheresRoute: typeof VendeurEncheresRoute
  VendeurHistoriqueRoute: typeof VendeurHistoriqueRoute
  VendeurPaiementsRoute: typeof VendeurPaiementsRoute
  VendeurVoituresRoute: typeof VendeurVoituresRoute
  VendeurIndexRoute: typeof VendeurIndexRoute
}

const VendeurRouteChildren: VendeurRouteChildren = {
  VendeurEncheresRoute: VendeurEncheresRoute,
  VendeurHistoriqueRoute: VendeurHistoriqueRoute,
  VendeurPaiementsRoute: VendeurPaiementsRoute,
  VendeurVoituresRoute: VendeurVoituresRoute,
  VendeurIndexRoute: VendeurIndexRoute,
}

const VendeurRouteWithChildren =
  VendeurRoute._addFileChildren(VendeurRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcheteurRoute: AcheteurRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  CommentCaMarcheAcheteurRoute: CommentCaMarcheAcheteurRoute,
  CommentCaMarcheVendeurRoute: CommentCaMarcheVendeurRoute,
  ExpertRoute: ExpertRouteWithChildren,
  HomeV2Route: HomeV2Route,
  HomeV3Route: HomeV3Route,
  InscriptionEnAttenteRoute: InscriptionEnAttenteRoute,
  LoginRoute: LoginRoute,
  TrustRoute: TrustRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VehiculesRoute: VehiculesRoute,
  VendeurRoute: VendeurRouteWithChildren,
  AuctionsAuctionIdRoute: AuctionsAuctionIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicAdminCreateUserRoute: ApiPublicAdminCreateUserRoute,
  ApiPublicAdminDeleteUserRoute: ApiPublicAdminDeleteUserRoute,
  ApiPublicCmiCallbackRoute: ApiPublicCmiCallbackRoute,
  ApiPublicCmiInitRoute: ApiPublicCmiInitRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
